api_key: 'key-e7d00a1a09400e7f0c3f93d0fd4a79be'
domain: 'sandbox6d05421ef8144a6faacdafc7dc919f4f.mailgun.org'
username: 'postmaster@sandbox6d05421ef8144a6faacdafc7dc919f4f.mailgun.org'
password: '5dbfc24f78fdd51ce7d42cc7d19695ed'
gmail_username: 'metzgersend@gmail.com'
gmail_password: 'password123!'
